version: '2'

networks:
  laraflix-net:

services:
  laraflix-db:
    image: 'bitnami/mariadb:latest'
    container_name: laraflix-db
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=laraflix
      - MARIADB_PASSWORD=secret
      - MARIADB_DATABASE=laraflix
    volumes:
        - './mariadb:/bitnami/mariadb'
    networks:
      - laraflix-net
    ports:
      - 3306:3306
  laraflix-api:
    image: docker.io/bitnami/laravel:8
    container_name: laraflix-api
    user: bitnami
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=laraflix
      - DB_PASSWORD=secret
      - DB_DATABASE=laraflix
    volumes:
      - './src:/app'
    depends_on:
      - laraflix-db
    networks:
      - laraflix-net